### ISSUE TITLE
Using `dnf` to install causes problems

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [zhullyb/dingtalk-for-fedora#1]
It seems that `dnf` installs it to `/opt/dingtalk-bin` by default, but the `Elevator.sh` is expecting `/opt/apps/com.alibabainc.dingtalk` and a completely different filesystem hierarchy.

Moving them to appropriate places, however, does not work. 

Have you managed to run DingTalk on Fedora? Please share how you did that!

**Comment by zhullyb** [comment]
> It seems that `dnf` installs it to `/opt/dingtalk-bin` by default, but the `Elevator.sh` is expecting `/opt/apps/com.alibabainc.dingtalk` and a completely different filesystem hierarchy.
> 
> Moving them to appropriate places, however, does not work.
> 
> Have you managed to run DingTalk on Fedora? Please share how you did that!

`Elevator.sh` is abandoned by me, run `/usr/bin/dingtalk`

**Comment by Ravenclaw-OIer** [comment]
Thanks! I've ran it successfully.
